/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}
dependencies {
    implementation(project(":domain"))

    implementation("com.mysql:mysql-connector-j:8.3.0")
    implementation("org.hibernate:hibernate-core:6.5.0.Final")



}