/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.f1race.backoffice;


public class App {
    public static void main(String[] args) {
        var backOffice = new BackOffice(System.in, System.out);

        backOffice.start();
    }
}
