/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":domain-implementations:jpa"))
    implementation(project(":domain-implementations:jdbc"))
}

application {
    // Define the main class for the application.
    mainClass = "cat.uvic.teknos.coursemanagement.services.Server"
}
