/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(project(":domain-implementations:jbdc"))
    implementation("de.vandermeer:asciitable:0.3.2")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
