CREATE DATABASE FORMULA1;
USE FORMULA1;

CREATE TABLE TEAM (
    TEAM_ID INT PRIMARY KEY,
    TEAM_NAME VARCHAR(50),
    PRINCIPAL_NAME VARCHAR(50),
    HEADQUARTERS VARCHAR(50),
    SPONSOR VARCHAR(50)
);

CREATE TABLE DRIVER (
    DRIVER_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    NATIONALITY VARCHAR(50),
    DATE_OF_BIRTH DATE,
    NUMBER INT,
    TEAM_ID INT,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE RACE_RESULT (
    RESULT_ID INT PRIMARY KEY,
    RACE_ID INT,
    DRIVER_ID INT,
    POSITION INT,
    FASTEST_LAP_TIME TIME,
    POINTS_EARNED INT,
    FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER(DRIVER_ID)
);

CREATE TABLE CAR (
    CAR_ID INT PRIMARY KEY,
    MODEL VARCHAR(50),
    ENGINE VARCHAR(50),
    CHASSIS VARCHAR(100),
    TEAM_ID INT,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE SPONSORSHIP (
    SPONSOR_ID INT PRIMARY KEY,
    SPONSOR_NAME VARCHAR(50),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    TEAM_ID INT,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

CREATE TABLE SPONSOR (
    SPONSOR_ID INT PRIMARY KEY,
    SPONSOR_NAME VARCHAR(100),
    COUNTRY VARCHAR(50),
    NUMBER INT,
    SPONSOR_TYPE VARCHAR(100),
    FOREIGN KEY (SPONSOR_ID) REFERENCES SPONSORSHIP(SPONSOR_ID)
);

select*from SPONSOR;