/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    // Dependencia para JUnit 5
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}