POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "teamName": "Haas F1 Team",
  "headquarters": "Kannapolis, NC",
  "sponsorName": "MoneyGram",
  "principalName": "Guenther Steiner"
}





